<h1><?= e($session['title']) ?></h1>
<p style="color:#666;font-size:10pt;margin:0 0 16px">Test Session Report &middot; <?= date('Y-m-d H:i') ?></p>

<h2>Session Details</h2>
<table style="max-width:600px">
  <tbody>
    <tr><th style="width:140px">Status</th><td><?= ucfirst(e($session['status'])) ?></td></tr>
    <?php if ($session['firmware_version']): ?>
    <tr><th>Firmware</th><td><?= e($session['firmware_version']) ?></td></tr>
    <?php endif; ?>
    <?php if ($session['app_version']): ?>
    <tr><th>App Version</th><td><?= e($session['app_version']) ?></td></tr>
    <?php endif; ?>
    <?php if ($area): ?>
    <tr><th>Test Area</th><td><?= e($area['name']) ?><?= $area['slope_max_percent'] ? ' (' . $area['slope_max_percent'] . '% slope)' : '' ?></td></tr>
    <?php endif; ?>
    <?php if ($session['weather_condition']): ?>
    <tr><th>Weather</th><td><?= e($session['weather_condition']) ?></td></tr>
    <?php endif; ?>
    <?php if ($session['temperature'] !== null): ?>
    <tr><th>Temperature</th><td><?= e($session['temperature']) ?> °C</td></tr>
    <?php endif; ?>
    <tr><th>Started</th><td><?= e($session['started_at']) ?></td></tr>
    <?php if ($session['ended_at']): ?>
    <tr><th>Ended</th><td><?= e($session['ended_at']) ?></td></tr>
    <?php endif; ?>
    <?php if ($session['terrain_notes']): ?>
    <tr><th>Terrain Notes</th><td><?= nl2br(e($session['terrain_notes'])) ?></td></tr>
    <?php endif; ?>
    <?php if ($session['description']): ?>
    <tr><th>Description</th><td><?= nl2br(e($session['description'])) ?></td></tr>
    <?php endif; ?>
  </tbody>
</table>

<h2>Entries (<?= count($entries) ?>)</h2>
<?php if ($entries): ?>
<table>
  <thead>
    <tr>
      <th style="width:80px">Date</th>
      <th style="width:70px">Type</th>
      <th style="width:95px">Serial</th>
      <th style="width:90px">Firmware</th>
      <th>Title / Description</th>
      <th style="width:65px">Status</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($entries as $ent): ?>
  <tr>
    <td><?= e($ent['entry_date']) ?></td>
    <td><?= e($ent['type_name'] ?? '') ?></td>
    <td><?= e($ent['mower_serial'] ?? '') ?></td>
    <td><?= e($ent['firmware_version'] ?? '') ?></td>
    <td><?= e($ent['title'] ?: mb_substr($ent['description'] ?? '', 0, 120)) ?></td>
    <td><?= e($ent['status']) ?></td>
  </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<?php else: ?>
<p style="color:#666">No entries linked to this session.</p>
<?php endif; ?>

<p style="color:#aaa;font-size:9pt;margin-top:24px">Generated by RoboDoc &middot; <?= date('Y-m-d H:i') ?></p>
